In [ ]:
import numpy as np
c = np.linspace(5,10,5)
c

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x=np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y=np.eye(3)#creates a matrixwith 1 as diagnol
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
z=np.eye(3,2)
z

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a=np.diag([1,2,3,4])# construct a adiagnol array
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
np.diag(a)#extracts the diagnol elements of matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#createsa array using random
a=np.random.rand(4)
a

array([0.28092203, 0.09189362, 0.15860025, 0.90375077])

In [ ]:
#wecan explicitly specifythrequired data type
a=np.arange(10,dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
b=np.array([1+2j, 5+1j])
print(b.dtype)

complex128


In [ ]:
c=np.array([True,False,True])
print(c.dtype)

bool


In [ ]:
a=np.arange(10)
print(a)
print(a[5])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
5
9


In [ ]:
b=np.diag([1,2,3])
print(b)
print(b[2,2])


[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [ ]:
b[2,1]=10 #assigning value to aindex
print(b)

[[ 1  0  0]
 [ 0  2  0]
 [ 0 10  3]]


In [ ]:
a=np.arange(10)
print(a[1:10:2])

[1 3 5 7 9]


In [ ]:
b=np.arange(10)
b[5:]=10 #assign 10 from index 5 to end
print(b)

[ 0  1  2  3  4 10 10 10 10 10]


COPIES AND VIEW


In [ ]:
a=np.arange(10)
b=a[::2]
np.shares_memory(a,b)

True

In [ ]:
b[0]=10
print(b)
print(a)#a is also updated,since is shares the same location in memory

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
c=a[::2].copy()#force the copy
np.shares_memory(a,c)

False

In [ ]:
c[0]=5
print(c)
print(a)

[5 2 4 6 8]
[10  1  2  3  4  5  6  7  8  9]


FANCY INDEXING


In [ ]:
a=np.random.randint(0,25,15)
print(a)

[11 22  6  5 21  3 18 23 13  2 12 22  6 22 12]


In [ ]:
mask=(a%2==0)

In [ ]:
even_numbers=a[mask]
print(even_numbers)

[22  6 18  2 12 22  6 22 12]


In [ ]:
a[mask]=-1#it can be very useful to assign a new value to sub array
print(a)

[11 -1 -1  5 21  3 -1 23 13 -1 -1 -1 -1 -1 -1]


USING INTEGER ARRAY


In [ ]:
a=np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
b=a[[2,3,5,2,4]]
print(b)

[20 30 50 20 40]


In [ ]:
a[[9,7]]=-200
print(a)
print(b)

[   0   10   20   30   40   50   60 -200   80 -200]
[20 30 50 20 40]


NUMERICAL OPERATIONS ON NUMPY
Element wise operation

In [ ]:
a=np.arange(10)
print(a+1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(a**2)

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
b=np.ones(10)+1
print("b= ",b)
print("a-b= ",a-b )

b=  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
a-b=  [-2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]


In [ ]:
print(a*b)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
#Matrix Multiplication
c=np.diag([1,2,3,4])
print(c)
print("*"*100)
print(c*c)
print("*"*100)
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
import numpy as np
a=np.array([1,2,5,4])
b=np.array([6,2,9,4])
print(a==b)

[False  True False  True]


In [ ]:
print(a>b)

[False False False False]


In [ ]:
print(a<b)

[ True False  True False]


In [ ]:
print(np.array_equal(a,b))

False


In [ ]:
c=np.array([1,2,5,4])
print(np.array_equal(a,c))

True


LOGICAL OPERATIONS

In [ ]:
a=np.array([1,0,0,1],dtype='bool')
b=np.array([0,1,0,1],dtype='bool')
print(np.logical_or(a,b))

[ True  True False  True]


In [ ]:
print(np.logical_not(a))

[False  True  True False]


In [ ]:
a=np.arange(5)+1
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


SHAPE MISMATCH


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,10])

print(a+b)

[ 2  5  8 14]


BASIC REDUCTION

In [ ]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [ ]:
y=np.array([[1,2],[3,4]])
print(y)
print("*"*100)
print(y.T)

[[1 2]
 [3 4]]
****************************************************************************************************
[[1 3]
 [2 4]]


In [ ]:
print(y.sum(axis=0))

[4 6]


In [ ]:
print(y.sum(axis=1))

[3 7]


In [ ]:
print(y.max())


4


In [ ]:
print(y.argmin())

0


In [ ]:
print(y.argmax())

3


LOGICAL REDUCTIONS

In [ ]:
print(np.all([True,False,False]))

False


In [ ]:
print(np.any([True,False,False]))

True


In [ ]:
a=np.zeros((50,50))
print(np.any(a!=0))

False


STATISTICS

In [ ]:
x=np.arange(1,10)
print(np.mean(x))

5.0


In [ ]:
print(np.median(x))

5.0


In [ ]:
y=np.array([[1,2,3],[4,5,6]])
print(np.mean(y,axis=0))
print(np.mean(y,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
print(np.std(x))

2.581988897471611


In [ ]:
Write a numpy program to covert a list of numeric value into a one-dimensional numpy array

In [ ]:
import numpy as np
list_of_numbers = [12.23, 13.32, 100, 36.32]
numpy_array = np.array(list_of_numbers)
print(numpy_array)

[ 12.23  13.32 100.    36.32]


Write a numpy program to create a 3x3 matrix with values ranging from 2 to 10

In [ ]:
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a numpy program to sort an along the first,last axis of an array

In [ ]:
import numpy as np
matrix = np.array([[7, 3, 4], [1, 8, 5], [9, 2, 6]])
sorted_rows = np.sort(matrix, axis=0)
sorted_columns = np.sort(matrix, axis=1)
print("Sorted rows:")
print(sorted_rows)

Sorted rows:
[[1 2 4]
 [7 3 5]
 [9 8 6]]


In [ ]:
Write a numpy program to create a contiguous flattened array.


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten(order='C')
print(flat_arr)


[1 2 3 4 5 6]


Write a numpy program to display all the dates for the month of MARCH,2017

In [ ]:
import numpy as np
dates=np.arange('2017-03-01','2017-04-01',dtype='datetime64[D]')
print("Month:march,2017")
print("Dates:"dates.tolist())

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-50-71acf5857576>, line 4)